### ISSUE TITLE
DataBridgesAPI requests library

### ISSUE THREAD

**Issue by ValerioGiuffrida** [WFP-VAM/DataBridgesAPI#2]
Revise the code as a library to get data from the various endpoints.
- [ ] manage credentials
- [ ] refresh token
- [ ] update endpoints dictionary
- [ ] extend endpoint methods

Also see #1

**Comment by ValerioGiuffrida** [comment]
@paololucchino @angeladiperna <- For your information!

@martinig94 thanks for your best effort on this!!

**Comment by paololucchino** [comment]
Thanks @ValerioGiuffrida for creating this and @martinig94 for the recent additions.

I'm looking into the possibility of automatically creating a complete python client (and potentially other languages too) based on the swagger.json. If curious: https://openapi-generator.tech/docs/installation for info. 

I created one based on the swagger in catalog.api.wfp.org in a branch here: https://github.com/WFP-VAM/DataBridgesAPI/tree/use-open-api-generator . I just need to get some credentials to try it out. Will let you know how it goes!
